### ISSUE TITLE
[Bug]: Unexpected "Reset" Action in CollectionChanged Event When Adding data to ReadOnlyObservableCollection from SourceList

### ISSUE THREAD

**Issue by SreemonPremkumarMuthukrishnan** [reactivemarbles/DynamicData#749] opened 2023-11-02 11:34 UTC
### Describe the bug 🐞

When binding a **DynamicData.SourceList** to a **ReadOnlyObservableCollection** in a WPF application, and then adding data to the SourceList, the **e.Action** property in the **CollectionChanged** event of the **ReadOnlyObservableCollection** is reported as "**Reset**" instead of "**Add**." However, when adding a data again to the SourceList, the **e.Action** property is reported as 'Add'.

**Code snippet:**
**Properties:**
```
private readonly SourceList<Person> _parentsSource = new SourceList<Person>();
public ReadOnlyObservableCollection<Person> Parents
{
    get;
}
```
**Codes:**
```
_parentsSource.Connect()
    .ObserveOn(RxApp.MainThreadScheduler)
    .Bind(out var parents)
    .Subscribe();

Parents = parents;
(Parents as INotifyCollectionChanged).CollectionChanged += MainWindow_CollectionChanged;

```
**Button click codes:**
```
private void AddADataButton_Click(object sender, RoutedEventArgs e)
{
    var data = new Person() { FirstName = "Data", LastName = "Data"};
    _parentsSource.Add(data);
}
```

### Step to reproduce

1. Run the sample.
2. Click the "ADD" button.
3. Ensure the Action property value shown in the MessageBox [i.e., "Reset"].
4. Again click the "ADD" button.
5. Ensure the Action property value shown in the MessageBox  [i.e.,"Add"].

### Reproduction repository

NA

### Expected behavior

The **e.Action** property in the **CollectionChanged** event of the **ReadOnlyObservableCollection** should be reported as "**Add**" when adding an item to the **SourceList**.

### Screenshots 🖼️

When adding the data for the first time.
![image](https://github.com/reactivemarbles/DynamicData/assets/104507189/cd4922f2-4939-467a-905a-bce65ddb2718)

When adding the data for second time.
![image](https://github.com/reactivemarbles/DynamicData/assets/104507189/9ffaa961-d507-4fac-9ed6-ca3a956cefd0)

I have attached the sample for the replication.

[ReadOnlyObservableCollection_SimpleSample.zip](https://github.com/reactivemarbles/DynamicData/files/13238252/ReadOnlyObservableCollection_SimpleSample.zip)

### IDE

Visual Studio 2022

### Operating system

Windows

### DynamicData Version

8.1.1

**Comment by RolandPheasant** [comment] 2023-11-02 21:51
The issue is cased by this [ObservableCollectionAdaptor.cs#L49](https://github.com/reactivemarbles/DynamicData/blob/043456887fc670e968e6e1c0130bfb73a53c6a65/src/DynamicData/Binding/ObservableCollectionAdaptor.cs#L49).

The Bind() operator is optimised to say if there are a greater number of rows changed than a specific reset threshold, then it's faster to fire a rest than it is to add one at a time.  However and probably quite bluntly it says lets just do a reset for the first notification, which seems excessively blunt.  This should probably be changed so it behaves the same whether it the the first notification, or subsequent one.

**Comment by SreemonPremkumarMuthukrishnan** [comment] 2023-11-15 11:32
Apologies for the delayed response. When can we expect a resolution for this issue?

**Comment by JakenVeina** [comment] 2023-11-18 01:18
Not that this isn't worth changing, but what's the scenario where it matters whether a `Reset` or an `Add` is published?

**Comment by RolandPheasant** [comment] 2023-11-22 08:28
> Not that this isn't worth changing, but what's the scenario where it matters whether a `Reset` or an `Add` is published?

If there's one thing I have learned about public code it's that people will consume it is ways which I would never anticipate.  Sometimes these ways are weird and wonderful and make no sense to me.  However I vaguely recall several issues with binding which arise from platform specifics, or from control suite limitations.   Although in an ideal world we would wash our hands of such things, it can seriously limit consumers.

What I have been thinking about is a simple solution to close of this debate once and for all. That is to provide system wide, static consumer settable defaults for binding.

Something like:

```cs
// these will be used to solve this issue
Binding.Defaults.ResetThreshold = 200;
Binding.Defaults.ResetOnFirstTimeLoad= true;.

// enable system wide custom adaptor.
Binding,ObservableCollection.List.DefaultAdaptor =  () => new MyObservableCollectionAdaptor<T>(); 
Binding,ObservableCollection.Cache.DefaultAdaptor =  () => new MyObservableCollectionAdaptor<T, K>(); 

Binding,BindingList.List.DefaultAdaptor =  () => new MyBindingListAdaptor<T>(); 
Binding,BindingList.Cache.DefaultAdaptor =  () => new MyBindingListAdaptor<T, K>(); 
```

In theory this will be a simple implementation and the operators will access these defaults., meaning it's probably getting the API right that's the most challenging part of this.

**Comment by dwcullop** [comment] 2023-11-26 18:43
> If there's one thing I have learned about public code it's that people will consume it is ways which I would never anticipate. Sometimes these ways are weird and wonderful and make no sense to me. 

They call it [Hyrum's Law](https://www.hyrumslaw.com/).  :smile:

> What I have been thinking about is a simple solution to close of this debate once and for all. That is to provide system wide, static consumer settable defaults for binding.

Simple solutions...
Add a new overload of the `Bind` method that supported a new bool parameter to control the behavior.

OR...

Just uniformly apply the threshold logic in all cases (e.g., If the initial changeset adds more than the threshold, then have it be a reset, otherwise, just have it be individual add events)

OR...

Combine the two:  Have the new parameter be the threshold to use for the initial event which can be different than the threshold used for all subsequent events...

Or is that too simplistic?

**Comment by JakenVeina** [comment] 2023-11-27 04:04
> What I have been thinking about is a simple solution to close of this debate once and for all. That is to provide system wide, static consumer settable defaults for binding.

So, the assumption is that `Refresh` changes aren't fully-supported for some platform-specific implementations of `INotifyPropertyChanged`?

**Comment by dwcullop** [comment] 2023-11-27 21:27
One way we could support all of those various libraries with their own version would be to put the library specific code into it's own NuGet package.  Then if you use DD and Library X, then you want the DD library but also the DD.LibraryX NuGet packages.  And then we could have specific code for all the popular libraries.  I'm not saying we should, I'm not sure how hard that would be...

**Comment by RolandPheasant** [comment] 2023-11-27 21:34
I think the problem with introducing more libraries is it could explode into way more than we wish to maintain. Whereas keeping it as a single library is comparatively simple.

**Comment by dwcullop** [comment] 2023-11-27 22:03
Agreed.  Furthermore, it doesn't have to be from this repo.  Anyone could make a NuGet package that uses the provided Adapter functionality to make library X easier to use.  Or it could even be part of Library X's repo.

**Comment by JakenVeina** [comment] 2023-11-28 04:45
It's a fairly common pattern to have multiple packages for a library with platform-specific code, I.E. `MyLibrary`, `MyLibrary.Wpf`, `MyLibrary.Uwp`, etc. And that's what we really _need_ to do if those platform-specific implementations have platform-specific dependencies (See https://github.com/dotnet/reactive/discussions/2038).

If we're just talking about a couple small classes that don't have any dependencies except to `ObservableCollection<T>` then yeah, I agree it's simpler to just keep them in the main package, and just make sure they're built to be trimmable.

**Comment by timothylcooke** [comment] 2023-11-29 16:57
The original use case was actually a ticket I opened with Syncfusion. I'm having issues in an app I'm building where their SfDataGrid properly updates, but their SfTreeGrid breaks. I opened the ticket with them. They said the problem is with DynamicData.

Here's the ticket I opened with Syncfusion:

> Sample app: [WpfTestApp.zip](https://github.com/reactivemarbles/DynamicData/files/13503110/WpfTestApp.zip)
> 
> Repro:
> 
> Launch the program,
> Click "Initial Seed",
> Click "Replace Children"
> 
> Now the SfTreeGrid is in a broken state. You can click "Add Child" or "Remove Child" as many times as you want. The SfDataGrid updates but the SfTreeGrid does not react to any changes in the children.
> 
> Pressing "Repopulate Tree" fixes the SfTreeGrid. You can press "Repopulate Tree" between steps 2 and 3 as well, to fix it. Once you repopulate tree once, it seems to be fixed forever (provided you repopulate tree after the initial seed).

My production app where I actually am running into issues has a very different use case, but the behavior is the same: the SfTreeGrid breaks while the SfDataGrid continues to handle updates. I'd rather use the SfTreeGrid in my application, but I'm stuck using the SfDataGrid.

Some source in my production app:

    this.WhenActivated(d => 
    {
        var imageFilesSource = new SourceCache<StudyImageFile, int>(x => x.LinkedImageId);

        d(imageFilesSource.Connect()
            .Transform(x => new ImageFileLoader(x))
            .Sort(SortExpressionComparer<ImageFileLoader>.Ascending(x => x.UniqueId))
            .ObserveOnDispatcher()
            .Bind(out var imageFiles)
            .DisposeMany()
            .Subscribe());
        ImageFiles = imageFiles;
        // Other code that actually fills the imageFilesSource based on results from API calls
    });
    [Reactive] public ReadOnlyObservableCollection<ImageFileLoader> ImageFiles { get; private set; }

Then, in my view:
    <sf:SfDataGrid x:Name="DataGrid" ItemsSource="{Binding ImageFiles}" ... />
and:
    <sf:SfTreeGrid ItemsSource="{Binding ImageFiles}" ... />

The `SfTreeGrid` breaks at some point but the `SfDataGrid` works fine.

From what I gather, this is more of a Syncfusion bug and less of a DD bug, but I don't really have the time to debug either library. Is there some logging I can add to my prod app that would help here?

**Comment by JakenVeina** [comment] 2023-11-30 09:05
It might be that we need to not be issuing resets at all. I do vaguely recall having WPF throw me some extensions not too long ago, when I was playing with a custom `INotifyCollectionChanged` implementation. There's types of reset actions that the `NotifyCollectionChangedEventArgs` constructor allows you to construct, that the binding system just.... doesn't support. Maybe that's what the Syncfusion folks are referring to, we're publishing a change action out of the binder that just isn't supported by the core binding system, and that kills the whole stream. So, it may not be the `Reset` change, per-se, but how it's constructed.

If you can give a minimal reproduction case, I'd absolutely be happy to look at it. I can try and re-create it myself, but no guarantees when I might get to that.

**Comment by RolandPheasant** [comment] 2023-12-03 23:20
I've introduced changes (not deployed yet) which allows the control of reset operations in dynamic data.

I have introduced code which enables binding to be turned off

```cs
 .Bind(out var parents, BindingOptions.NeverFireReset())
```

and it seems to fix the issue.  Annoyingly I have to grab a free trial of Synch Fusion to test!

See description of this https://github.com/reactivemarbles/DynamicData/pull/776 for more details.  It will be released soon.

BTW I advise not to turn off reset threshold system wide as it is a seriously important performance optimisier

**Comment by RolandPheasant** [comment] 2023-12-04 23:51
Hopefully fixed by https://github.com/reactivemarbles/DynamicData/pull/776.  Will release in next few days

**Closed by RolandPheasant** 2023-12-04 23:51 UTC
Labels: bug

**Comment by timothylcooke** [comment] 2023-12-04 23:57
Thanks, @RolandPheasant.

On a side note, I've spent about the last two hours trying -- and failing -- to create a minimal repro of the issue I'm running into in my production app. Makes me wonder if I'm doing something silly in my app. Hopefully I'll have more time to spend on this tomorrow. Will follow up if I manage to reproduce. Otherwise, assume I'm happy 🙂
