### ISSUE TITLE
Possible memory leak with usage of "ToObservableChangeSet" with "expireAfter"

### ISSUE THREAD

**Issue by jholzer** [reactivemarbles/DynamicData#305] opened 2019-11-27 15:36 UTC
**Description**

When filling a cache from an observable using "ToObservableChangeSet" with "expireAfter" and "AsObservableCache" memory keeps groving.

See example code below and description how to see issue...

`ExpiringCache = itemSource
                .ToObservableChangeSet(vt => vt.Guid, i => TimeSpan.FromSeconds(5), 5)
                    .AsObservableCache();`

**Steps To Reproduce**

1. Start attached program to reproduce issue
2. When program running with Visual Studio (i use 2019 Pro) go to "Diagnostic Tools" => "Memory Usage" and click on "Take Snapshot"
3. After some time (e.g. 15-20 seconds) take a second snapshot
4. Compare the snapshots by clicking on the "Object (diff)" cell of the second snapshot

In comparison loads of "ExpirableItems" inside dictionaries can be seen (see screenshot below).

It seems like when expired objects are removed from cache some helper objects are still kept alive.

Long term memory profiling of similar setup with larger objects show increasing memory.

**Expected behavior**

Memory should not keep growing after expire-threshold
**Screenshots**

![image](https://user-images.githubusercontent.com/15092942/69736673-482af300-1133-11ea-8c29-bb87789e8198.png)

**Environment**
- OS:       Windows 10
- Device:   PC
- Version:   DynamicData 6.13.21
- Working Version: n/a

**Additional context**

[ExpireTest.zip](https://github.com/reactiveui/DynamicData/files/3897528/ExpireTest.zip)

**Comment by RolandPheasant** [comment] 2019-11-27 16:22
Thanks for raising this. I will investigate as soon as I can

**Comment by RolandPheasant** [comment] 2019-11-30 10:07
The issue is due to a leak in another operator (GroupWithImmutableState) which is used by the time based expirer.

Looking at the code I think the expiring cache is over engineered, I do not know what I was thinking at the time. What I will do is to a) simplify the expiring code b) separately fix the original leak

**Comment by RolandPheasant** [comment] 2019-11-30 10:12
Looking at the API again, the reason for the complexity is that time based expiration can be dependent on individual elements. I remember now that the use case I programmed the API against was that I needed to keep high important items in the cache always and to remove lower priority items with sliding time according to the status.

**Comment by jholzer** [comment] 2019-11-30 12:48
Good to read that you could identify the issue!
I´m also aware of the element-depending exipration of elemens. We are using this on other occasions.
Would be could if you could keep both features... :-)

**Comment by RolandPheasant** [comment] 2019-12-07 12:51
The fix has been deployed in [v6.14.1](https://www.nuget.org/packages/DynamicData/6.14.1). Please let me know if it fixes the issue.

This also leads to another problem in that time based grouping  (or any impure group function) for GroupOnImmutable will also leak.  I will fix this in the near future.

**Comment by jholzer** [comment] 2019-12-09 07:38
Hi Roland! 

Thanks for the quick response and release.

But unfortunately it didn´t fix the issue.
After update to 6.14.1.49947 we´re still gettting the growing memory with both out productive code as well as the small "ExpireTest"-Tool (see above).

![image](https://user-images.githubusercontent.com/15092942/70416102-87741080-1a5e-11ea-87c7-5488764d9435.png)

Given the code above (pretty similar to productive code snippet, just different objects): 
Is there something we should change in the usage of "expireAfter"?

**Comment by RolandPheasant** [comment] 2019-12-09 22:18
There is nothing which you are doing wrong. I need to take a further look.

**Comment by jholzer** [comment] 2019-12-10 18:03
Ok. Thank you!

**Comment by cparaskeva** [comment] 2020-02-25 18:56
Hello, any updates on the issue?

**Closed** 2022-06-09 19:19 UTC
Labels: bug, todo :spiral_notepad:
