### ISSUE TITLE
EditDiff issue for Xamarin.iOS 

### ISSUE THREAD

**Issue by FelipeAvilaMachado** [reactivemarbles/DynamicData#342] opened 2020-03-30 15:19 UTC
**Describe the bug**

Hi, I've been using DynamicData and ReactiveUI on my projects, i must say I'm really impressed with those projects, awesome work!

But unfortunately not everything is perfect, found an few issues here and there, messing with threads can be complicated... (learned a lot in the last few weeks! haha)

Anyway, I've created an Xamarin Forms AutoCompleteView that filters ItemsSource based on user input and update the SourceCache that binds to an ReadOnlyObservableCollection and display on an CollectionView.

For performance reasons, i have created an in-memory SQLite connection that creates when the ItemsSource change so the filters and sorting runs faster.

While this is working just fine for Android, it some times throw an Exception on iOS while the user is typing.

This seams to be an Xamarin.iOS Bug, but i'm posting this here just to be sure.
I'll be posting on Xamarin Forms as well if confirmed.

**Steps To Reproduce**

Simplified code:

                        auto.SourceCache
                            .Connect()
                            .Bind(out auto.Items)
                            .Subscribe();

                        auto.WhenAnyValue(a => a.MainEntry.Text)
                            .Throttle(TimeSpan.FromMilliseconds(400), RxApp.MainThreadScheduler)
                            .Where(_ => auto.MainEntry.IsFocused)
                            .Select(t => string.IsNullOrWhiteSpace(t) ? string.Empty : t.Trim())
                            .DistinctUntilChanged()
                            .ObserveOn(RxApp.MainThreadScheduler)
                            .SubscribeOn(RxApp.MainThreadScheduler)
                            .Subscribe(_ =>
                            {
                                var newItems = new List<Item>();
                                var cmd = auto.Connection.CreateCommand();
                                cmd.CommandText = "SELECT * FROM Items WHERE Value LIKE @SEARCH ORDER BY Value ASC LIMIT 6";
                                cmd.Parameters.AddWithValue("@SEARCH", $"%{_}%");
                                var reader = cmd.ExecuteReader();
                                while (reader.Read())
                                {
                                    var id = reader.GetFieldValue<int>(0);
                                    var value = reader.GetFieldValue<string>(1);
                                    newItems.Add(new Item(id, value));
                                }
                                auto.SourceCache.EditDiff(newItems, (oldI, newI) => oldI.Id == newI.Id);
                            });

Update:
With SourceList it won't crash, only with SourceCache.
Tried utilizing Edit on SourceCache as well but still crashs, only worked with SourceList.

Workaround:

                                if (Device.RuntimePlatform == Device.Android)
                                {
                                    auto.SourceCache.EditDiff(newItems, (oldI, newI) => oldI.Id == newI.Id);
                                }
                                else
                                {
                                    auto.SourceList.Edit(items =>
                                    {
                                        items.Clear();
                                        items.AddRange(newItems);
                                    });
                                    auto.SourceList.EditDiff(newItems);
                                }

**Expected behavior**

List updating just fine

**Screenshots**

**Environment**

- OS: iOS       
- Device: iPhone Simulator  
- Version: 13.3  
- Working Version: Android?

**Additional context**

StackTrace:
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:161 
  at System.Collections.ObjectModel.Collection`1[T].get_Item (System.Int32 index) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/ObjectModel/Collection.cs:46 
  at System.Collections.ObjectModel.ReadOnlyCollection`1[T].System.Collections.IList.get_Item (System.Int32 index) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/ObjectModel/ReadOnlyCollection.cs:223 
  at Xamarin.Forms.Platform.iOS.ObservableItemsSource.ElementAt (System.Int32 index) [0x0000f] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:268 
  at Xamarin.Forms.Platform.iOS.ObservableItemsSource.get_Item (System.Int32 index) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:37 
  at Xamarin.Forms.Platform.iOS.ObservableItemsSource.get_Item (Foundation.NSIndexPath indexPath) [0x00019] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:93 
  at Xamarin.Forms.Platform.iOS.ItemsViewController`1[TItemsView].UpdateTemplatedCell (Xamarin.Forms.Platform.iOS.TemplatedCell cell, Foundation.NSIndexPath indexPath) [0x00012] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:221 
  at Xamarin.Forms.Platform.iOS.ItemsViewController`1[TItemsView].GetCell (UIKit.UICollectionView collectionView, Foundation.NSIndexPath indexPath) [0x00033] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:85 
  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr_IntPtr(intptr,intptr,intptr,intptr)
  at UIKit.UICollectionView.PerformBatchUpdates (System.Action updates, UIKit.UICompletionHandler completed) [0x00055] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.14.1.39/src/Xamarin.iOS/UICollectionView.g.cs:568 
  at Xamarin.Forms.Platform.iOS.ObservableItemsSource.Remove (System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x0004e] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:210 
  at Xamarin.Forms.Platform.iOS.ObservableItemsSource.CollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x0002c] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:117 
  at Xamarin.Forms.Platform.iOS.ObservableItemsSource.CollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x0002d] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:105 
  at System.Collections.ObjectModel.ReadOnlyObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ReadOnlyObservableCollection.cs:81 
  at System.Collections.ObjectModel.ReadOnlyObservableCollection`1[T].HandleCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ReadOnlyObservableCollection.cs:133 
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00018] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:263 
  at DynamicData.Binding.ObservableCollectionExtended`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00009] in <0428feb0fa694c14962926a6d6db824f>:0 
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedAction action, System.Object item, System.Int32 index) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:338 
  at System.Collections.ObjectModel.ObservableCollection`1[T].RemoveItem (System.Int32 index) [0x00021] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:182 
  at System.Collections.ObjectModel.Collection`1[T].Remove (T item) [0x00027] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/ObjectModel/Collection.cs:128 
  at DynamicData.Binding.ObservableCollectionAdaptor`2[TObject,TKey].DoUpdate (DynamicData.IChangeSet`2[TObject,TKey] updates, DynamicData.Binding.IObservableCollection`1[T] list) [0x00043] in <0428feb0fa694c14962926a6d6db824f>:0 
  at DynamicData.Binding.ObservableCollectionAdaptor`2[TObject,TKey].Adapt (DynamicData.IChangeSet`2[TObject,TKey] changes, DynamicData.Binding.IObservableCollection`1[T] collection) [0x00077] in <0428feb0fa694c14962926a6d6db824f>:0 
  at DynamicData.ObservableCacheEx+<>c__DisplayClass153_0`2[TObject,TKey].<Bind>b__1 (DynamicData.IChangeSet`2[TObject,TKey] changes) [0x00000] in <0428feb0fa694c14962926a6d6db824f>:0 
  at System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult].OnNext (TSource value) [0x00000] in <b083c4e360dc40a6b457074d604e68fd>:0

**Comment by se** [comment] 2021-01-28 22:24
Any update on this?

**Comment by nathanpovo** [comment] 2021-06-22 10:14
I ran into this and was getting the exception

> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

In my case, the issue was due to me using the same `IObservable` in two different pipelines and subscribing to them separately

```csharp
IObservable<IChangeSet<string, int>> myObservable = myObservableCache
    .Connect();

myObservable
    .Subscribe();

myObservable
    .OnItemAdded(OnItemAddedImpl)
    .Subscribe();

myObservable
    .OnItemRemoved(OnItemRemovedImpl)
    .Subscribe();
```

If you are using the same `IObservable` in more than one pipeline you have to convert it to a hot observable:

```csharp
IConnectableObservable<IChangeSet<string, int>> myHotObservable = myObservableCache
    .Connect()
    .Publish(); // Converts the IObservable to a IConnectableObservable

// Connect the IConnectableObservable
// The observable will start working at this point
// Make sure to dispose this
myHotObservable
    .Connect();

myHotObservable
    .OnItemAdded(OnItemAddedImpl)
    .Subscribe();

myHotObservable
    .OnItemRemoved(OnItemRemovedImpl)
    .Subscribe();
```

Note that the two `Connect` methods are different.

**Comment by RolandPheasant** [comment] 2022-05-05 15:05
Is there anyone out there who can replicate this problem in Xamarin.IOS?

I'll need help as I am not a Xamarin developer.  All edit diff does if to calculate a diff set and does absolutely nothing special see [EditDiff.cs
](https://github.com/reactivemarbles/DynamicData/blob/main/src/DynamicData/Cache/Internal/EditDiff.cs) and then uses standard internal mechanisms to create changes sets.

**Comment by RolandPheasant** [comment] 2022-05-23 18:31
None has provided reproducible code so I am closing this. If the issue occurs, try the suggested fix above and if that fails please raise an issue with some demo code

**Closed by RolandPheasant** 2022-05-23 18:31 UTC
Labels: bug, help wanted
